Add support to have shellscript workers part of pipeline too
adobe/asset-compute-pipeline pull request #79
Opened 2023-11-28 19:53 UTC by tmathern

## Description

- Handling some more cases for test mode

Fixes # (issue)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-11-28 23:33 UTC, badvision approved these changes
Fair, though if there is a way in the future to extract metadata (unlikely though) we should revisit this.

2023-11-28 23:39 UTC, pheenomenon commented on lib/metadata.js
> +        fileExtension = fileExtension?.slice(1);
we don't need this here ?

2023-11-28 23:42 UTC, pheenomenon requested changes
remove likely dead code ?

2023-11-28 23:57 UTC, tmathern commented on lib/metadata.js
> +        fileExtension = fileExtension?.slice(1);
Good catch

2023-11-28 23:58 UTC, tmathern commented
> remove likely dead code ?

Done!

2023-11-29 00:01 UTC, pheenomenon approved these changes

2023-11-29 03:17 UTC, merged